### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by apanagio** [dcm4che/dcm4chee-arc-cdi#18]
Hi guys,
It seems that the release repository (http://www.dcm4che.org/maven2/) is not holding the expected versions causing errors when attempting to build the project

best regards
Alexis

**Comment by hczedik** [comment]
Hi,

which artifacts are missing?
Please post the output of the maven command.

Thanks,
Hermann

**Comment by hczedik** [comment]
The version on master references SNAPSHOT versions of other dcm4che projects.
You will probably need to build those first.
At least:
* The dcm4che 3 library ( https://github.com/dcm4ch )
* The configuration layer ( https://github.com/dcm4che/dcm4chee-conf )
* The storage layer ( https://github.com/dcm4che/dcm4chee-storage2 )

**Comment by apanagio** [comment]
thanks for the quick reply,
you were right I had to build the packages you mentioned first.
However I still cannot build the project, I get a NullPointerException when building dcm4chee-arc-entity.
I'm posting the stack trace in case it's helpful:

``[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (generate-create-schema-ddl) on project dcm4chee-arc-entity: An exception occured while executing the Java class. null: InvocationTargetException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (generate-create-schema-ddl) on project dcm4chee-arc-entity: An exception occured while executing the Java class. null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:338)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:283)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.blogspot.doingenterprise.SchemaExport.main(SchemaExport.java:42)
	... 6 more
``

**Comment by Hesham-Elbadawi** [comment]
Hi Alex,

Please use :
mvn clean install -Ddb=mysql

If you are building for mysql.


Kind Regards,

MSc. Hesham Elbadawi | Agfa HealthCare
R&D Software Developer | HE/R&D Impax EE
T  +43189966 315 | F  +43189966 110 | M +4369910928505

Agfa HealthCare GmbH, Diefenbachgasse 35, 1150 Wien, Austria
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Geschäftsführer: Dkfm. Winfried Post | Sitz der Gesellschaft: Wien, Handelsgericht Wien, FN 56704p | UID ATU15133905
Click on link to read important disclaimer: http://www.agfahealthcare.com/maildisclaimer

**Comment by apanagio** [comment]
Hi Hesham,

thanks for the tip. Indeed I needed to do that.
Just in case somebody lands here I'll mention that I needed to build dcm4chee-monitoring as well.

thanks again
Alexis
