### ISSUE TITLE
Getting WELD-001408: Unsatisfied dependencies for type Hooks<DefaultPersonNameManager> with qualifiers @Default

### ISSUE THREAD

**Issue by kamal-1984** [dcm4che/dcm4chee-arc-cdi#23]
I have taken the code from GITHUB for dcm4chee-arc-cdi project,i have built the code using Maven as specified in the link.it successfully generated the dcm4chee-arc-ear file.

Now when i try to deploy the ear file into JBOSS wildfly server version( wildfly-8.2.0.Final) iam getting the dependencies issue.

19:48:29,958 ERROR [org.jboss.msc.service.fail](MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear".WeldStartService: Failed to start service
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Hooks<DefaultPersonNameManager> with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject @Limit private org.dcm4chee.archive.store.impl.StoreServiceEJB.personNameSelector
  at org.dcm4chee.archive.store.impl.StoreServiceEJB.personNameSelector(StoreServiceEJB.java:0)

```
at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:372)
at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:293)
at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:531)
at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_79]
... 3 more
```

19:48:30,042 ERROR [org.jboss.as.controller.management-operation](Controller Boot Thread) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear")]) - failure description: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Hooks<DefaultPersonNameManager> with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject @Limit private org.dcm4chee.archive.store.impl.StoreServiceEJB.personNameSelector
  at org.dcm4chee.archive.store.impl.StoreServiceEJB.personNameSelector(StoreServiceEJB.java:0)
"}}
19:48:30,090 INFO  [org.jboss.as.server](ServerService Thread Pool -- 31) JBAS018559: Deployed "postgresql-9.4-1201-jdbc41.jar" (runtime-name : "postgresql-9.4-1201-jdbc41.jar")
19:48:30,091 INFO  [org.jboss.as.server](ServerService Thread Pool -- 31) JBAS018559: Deployed "dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear" (runtime-name : "dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear")
19:48:30,104 INFO  [org.jboss.as.controller](Controller Boot Thread) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."dcm4chee-arc-ear-4.5.0-SNAPSHOT-psql.ear".WeldStartService: Failed to start service

**Comment by hczedik** [comment]
arc-cdi is no longer maintained. Please use [dcm4chee-arc-light](https://github.com/dcm4che/dcm4chee-arc-light) instead.

**Comment by kamal-1984** [comment]
i think OPEN LDAP is required to work with dcm4chee-arc-light.I am facing few issues while configuring the Open Ldap.
Can i use dcm4chee-arc-light as my DICOM server without the LDAP.

**Comment by gunterze** [comment]
You need a LDAP server for running dcm4chee-arc-light. It need not be Open LDAP. Another option is to run it in on docker, so you can use a docker image including preconfigured Open LDAP for dcm4chee-arc-light: https://hub.docker.com/r/dcm4che/slapd-dcm4chee
